name: TerrariaItems
version: '1.0-SNAPSHOT'
main: me.carson.terrariaItems.TerrariaItems
api-version: '1.21'
commands:
  ti:
    description: Terraria Items main command
    usage: /ti <subcommand>
    permission: terrariaitems.ti
    permission-message: You don't have permission to use this.
permissions:
  terrariaitems.ti:
    description: Allows access to /ti command
    default: not op
  terrariaitems.sub.give:
    description: Terraria Items Commands
    default: op
  terrariaitems.sub.toggle_message:
    description: Terraria Items Commands
    default: not op